KOCHKA: remove problematic tests
Seems like our CI is failing on these tests with the following error:

```text
TypeError: /home/runner/work/universe/universe/src/kochka.com.mx/.babelrc.js: Error while loading config - /home/runner/work/universe/universe/src/kochka.com.mx/.babelrc.js: Error while loading config - (0 , _helperCompilationTargets(...).isBrowsersQueryValid) is not a function
```

It is a bit strange because it behaves differently locally. However, I'd like to remove these tests to see if it helps since CI always points at these. I do not know what's the actual issue, so I will create a TODO to revert this change.

adeira-source-id: 27ea03d866bed1fefc778180ac270f2f1c3e4e57